### ISSUE TITLE
Missing a starting documentation

### ISSUE THREAD

**Issue by fulup-bzh** [mschlappa/fhem#1]
I'm trying to use your script with a pm30 and would appreciated a small readme with some syntax samples. 

When starting your script (Linux OpenSuse-15) I have few error message:
- (did you forget to declare "my $readingFnAttributes"?) 
- syntax error at 70_KEBA.pm line 170, near "Log 3"

Can you script run by it's own ? If then what is the launching syntax.

Thank you
Fulup

**Comment by mschlappa** [comment]
Hello,

my script only works together with fhem home automation: https://fhem.de/

Marcus

**Comment by fulup-bzh** [comment]
This is what I was afraid of, my goal was only to check a small tools to send raw low level command and check the protocol. I full house automation if far too much for my current objective.
Thank you for your quick response.
